[package]
name = "spaligner"
version = "0.1.0"
authors = ["c0deb0t <daniel.liu02@gmail.com>"]
edition = "2018"

[dependencies]
debruijn = "0.3.2"
serde = "^1"
serde_derive = "^1"

[dependencies.hashbrown]
version = "0.9"
features = ["serde"]
